config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get 'sessions/new'

  resources :users, only: [:new,:create,:show]
  resources :users

  resources :sessions,only:[:new,:create,:destroy]

  resources :feeds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :feeds do
    collection do
      post :confirm
    end
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                    before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :feeds
  has_many :favorites,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿をお気に入り解除しました"
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]


  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
    @user = User.find_by(id: @feed.user_id)
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    render :new if @feed.invalid?
  end

  def edit; end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    if @feed.save
      FeedMailer.feed_mail(@feed).deliver
      redirect_to feeds_path(@feed.id), notice: '投稿が完了しました'
    else
      render :new
    end
  end

  def update
    @feed.user_id = current_user.id
    if @feed.update(feed_params)
      redirect_to @feed, notice: '投稿を編集しました'
    else
      render :edit
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: '投稿を削除しました' }
      format.json { head :no_content }
    end
  end

  private

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash[:danger] = 'ログインに失敗しました'
        render 'new'
      end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path(@user_id),notice: '新規アカウントを作成しました'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @feeds = Feed.all
    @favorites = current_user.favorites.all
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/views/feeds/_form.html.erb
<%= form_with(model: @feed, local: true, url:choose_new_or_edit) do |form| %>

  <div class="field">
    <tr>
      <td><h3><%= form.label :写真を選ぶ %></h3></td><br>
      <td><%= image_tag(@feed.image.url,size:"320x480") if @feed.image.url %></td><br><br>
      <td><%= form.file_field :image, id: :feed_image %></td><br><br>
      <td><h3><%= form.label :コメントを入力 %></h3></td><br>
      <td><%= form.text_field :content %></td>
    </tr>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<div class="new_picture" >
  <div class="well well-lg">
    <%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
      <%= image_tag(@feed.image.url,size:"320x480") %>
      <%= form.hidden_field :image_cache %>
      <%= form.label :コメント %>
      <%= form.text_field :content %>
      <%= form.submit "投稿する" %>
    <% end %>
    <br>
    <%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image_cache %>
      <%= form.submit "戻る", name: "back" %>
    <% end %>
  </div>
</div>

app/views/feeds/edit.html.erb
<h1>写真を編集する</h1>
<div class="new_picture" >
  <div class="well well-lg">
  <%= render 'form', feed: @feed %><br>
  <h4><%= link_to '詳細', @feed %></h4><br>
  <h4><%= link_to '戻る', feeds_path %></h4>
  </div>
</div>

app/views/feeds/index.html.erb
<p id="pageTop"><a href="#">top</i></a></p>
<h1>ユーザーの写真</h1>

<table class="table"></div>
  <thead>
    <tr>
      <th><h3>Image</h3></th>
      <th><h4>コメント</h4></th>
      <th><h4>投稿者</h4></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= link_to (image_tag feed.image,size:"320x480"),feed,class:"pc"%><%= link_to (image_tag feed.image,size:"160x240"),feed,class:"sp" %></td>
        <td><br><%= feed.content %></td>
        <td><h4><%= feed.user.name %></h4></td>
      </tr>
      <tr>
        <td><h4><%= link_to '投稿を見る', feed %></h4></td>
        <td><h4><%= link_to '編集する', edit_feed_path(feed) %></h4></td>
        <td><h4><%= link_to '削除する', feed, method: :delete, data: { confirm: 'Are you sure?' } %></h4></td>
      </tr>
      <tr>
        <th><h3>Image</h3></th>
        <th><br><h4>コメント</h4></th>
        <th><br><h4>投稿者</h4></th>
        <th colspan="3"></th>
      </tr>
    <% end %>
  </tbody>
</table><br>

<h4 class="new_buttan"><%= link_to '新しく投稿する', new_feed_path %></h4>

app/views/feeds/new.html.erb
<h1>新しく投稿する</h1>
<div class="new_picture" >
  <div class="well well-sm">
    <%= render 'form', feed: @feed %>
    <%= link_to '戻る', feeds_path %>
  </div>
</div>

app/views/feeds/show.html.erb
<h1>写真の詳細</h1>

<div class="new_picture" >
  <div class="well well-lg">
    <h3>Image</h3>
    <%= image_tag @feed.image,size:"480x720" %>
    <h4>投稿者：<%= @user.name %></h4><br>
    <h4><%= link_to '編集する', edit_feed_path(@feed) %></h4><br>
    <h4><%= link_to '戻る', feeds_path %></h4><br>

    <% unless @feed.user_id == current_user.id %>
      <% if @favorite.present? %>
        <h4><%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %></h4>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="container">
    <header class="header"><%= link_to "Instagram", new_session_path %></header>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

    <article>
      <div class="contents">
        <ul class="row">
          <% if logged_in? %>
          <li class="col-sm-6 col-md-6"><%= link_to "Profile", user_path(current_user.id) %></li>
          <li class="col-sm-6 col-md-6"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          <% else %>
          <li class="col-sm-6 col-md-6"><%= link_to "Sign up", new_user_path %></li>
          <li class="col-sm-6 col-md-6"><%= link_to "Login", new_session_path %></li>
          <% end %>
          <%= yield %>
        </ul>
      </div>
    </article>
  </div>
</html>

app/views/users/index.html.erb
<p id="pageTop"><a href="#">top</i></a></p>
<h1>お気に入りの写真</h1>

<div class="well">
  <tbody>
    <% @favorites.each do |favorite| %>
      <%= image_tag favorite.feed.image,size:"160x240" %>
    <tr>
      <!-- <td> コメント:<%= favorite.feed.content %></td> -->
      <td> 投稿者:<%= favorite.feed.user.name %></td>
    </tr>
    <% end %>
  </tbody>
</div>
<h4><%= link_to '戻る', feeds_path %></h4>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h2>新しいアカウントを作ります</h2>

<div class ="login_form">
  <div class="container">
    <ul class="row">
      <%= form_with(model: @user, local: true) do |f| %>
        <p class="col-sm-12 col-md-12">
        <%= f.label :name %></p>
        <p class="col-sm-12 col-md-12">
        <%= f.text_field :name %></p>
        <p class="col-sm-12 col-md-12">
        <%= f.label :email %></p>
        <p class="col-sm-12 col-md-12">
        <%= f.email_field :email %></p>
        <p class="col-sm-12 col-md-12">
        <%= f.label :password %></p>
        <p class="col-sm-12 col-md-12">
        <%= f.password_field :password %></p>
        <p class="col-sm-12 col-md-12">
        <%= f.label :password_confirmation %></p>
        <p class="col-sm-12 col-md-12">
        <%= f.password_field :password_confirmation %></p>
    </ul>
        <br><%= f.submit "新しいアカウントを作る" %>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>What are you doing now?, <%= @user.name %>.</h1><br><br>

<div class="list-group">
<%= link_to "写真を投稿する", new_feed_path,class: "list-group-item" %>
<%= link_to "ユーザーの写真を見る",feeds_path,class: "list-group-item"%>
<%= link_to 'お気に入りの写真', users_path,class: "list-group-item" %>
</div>